{{- if .Values.ontoserver.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gw
  annotations:
  {{ toYaml .Values.ontoserver.gateway.annotations indent 4}}
  {{- if .Values.ontoserver.gateway.certmanager.enabled }}
    cert-manager.io/issuer: letsencrypt-{{ .Release.Name }}
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
  {{- end }}
spec:
  gatewayClassName: {{ .Values.ontoserver.gateway.className }}
  infrastructure:
    annotations: {{ toJson .Values.ontoserver.gateway.infrastructureAnnotations }}      
  listeners:
  {{- if .Values.ontoserver.gateway.certmanager.enabled }}
  # Cert Manager Listener
    - name: public-http
      protocol: HTTP
      port: 80 # This should be always port 80 as per https://cert-manager.io/docs/configuration/acme/http01/#configuring-the-http-01-gateway-api-solver
      allowedRoutes:
        namespaces:
          from: Same
  {{- end }}
  {{ $releaseName := .Release.Name }}
  {{- range.Values.atomio.gateway.route.hostNames }}
    - name: websecure
      hostname: {{ . }}
      port: {{ $.Values.ontoserver.gateway.listenerPortSecure }}
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ $releaseName }}-tls
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: atomio-route
spec:
  hostnames:
    {{- range.Values.atomio.gateway.route.hostNames }}
    - {{ . }}
    {{- end }}
  parentRefs:
    - group: gateway.networking.k8s.io
      sectionName: websecure
      kind: Gateway
      name: {{ .Release.Name }}-gw
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Release.Name }}-atomio-service
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: "{{ .Values.ontoserver.gateway.requestTimeout }}"
        backendRequest: "{{ .Values.ontoserver.gateway.requestTimeout }}"
{{- if .Values.ontoserver.gateway.certmanager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    email: {{ .Values.ontoserver.certmanager.email }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: {{ .Release.Name }}-gw
                namespace: {{ .Release.Namespace }}
                kind: Gateway
{{- end }}
{{- end }}