{{- if .Values.ontoserver.deployment.persistence.enabledForDeployment }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ontoserver-files
spec:
  {{- if .Values.ontoserver.deployment.persistence.existingVolume.enabled }}
  volumeName: {{ .Values.ontoserver.deployment.persistence.existingVolume.name }}
  {{- else }}
  resources:
    requests:
      storage: "{{ required "ontoserver.resources.ontoserver.requests.storage is required" .Values.ontoserver.resources.ontoserver.requests.storage }}"
  accessModes:
    - ReadWriteOnce
  {{- if .Values.ontoserver.deployment.persistence.storageClass.provided.enabled }}
  storageClassName: {{ .Release.Name }}-ontoserver-files-retain
  {{- else }}
  storageClassName: {{ .Values.ontoserver.deployment.persistence.storageClass.name }}
  {{- end }}
  {{- end }}
{{- end }}