{{- if eq .Values.ontoserver.deployment.kind "StatefulSet" }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-statefulset
spec:
  {{- if eq .Values.ontoserver.deployment.type "scaled" }}
    {{- if eq (int .Values.ontoserver.deployment.replicas) 1 }}
      {{- fail "scaled deployments require ontoserver.deployment.replicas should be greater or equal to 2 or 0" }}
    {{- end }}
  {{- else if eq .Values.ontoserver.deployment.type "single" }}
    {{- if gt (int .Values.ontoserver.deployment.replicas) 1 }}
      {{- fail "single deployments require ontoserver.deployment.replicas < 2" }}
    {{- end }}
  {{- else }}
    {{- fail "ontoserver.deployment.type not recognised. Must be single or scaled" }}
  {{- end }}
  replicas: {{ .Values.ontoserver.deployment.replicas }}
  podManagementPolicy: Parallel
  serviceName: {{ .Release.Name }}-headless
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ontoserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ontoserver
    spec:
      {{- if .Values.ontoserver.imagePullSecrets }}
      imagePullSecrets: {{ toJson .Values.ontoserver.imagePullSecrets }}
      {{- end}}
      {{- if .Values.ontoserver.tolerations }}
      tolerations: {{ toJson .Values.ontoserver.tolerations }}
      {{- end}}
      containers:
        - name: {{ .Release.Name }}-ontoserver
          image: {{ required "ontoserver.image is required " .Values.ontoserver.image }}
          imagePullPolicy: {{ required "ontoserver.imagePullPolicy is required" .Values.ontoserver.imagePullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ required "ontoserver.resources.ontoserver.requests.cpu is required" .Values.ontoserver.resources.ontoserver.requests.cpu }}
              memory: {{ required "ontoserver.resources.ontoserver.requests.memory is required" .Values.ontoserver.resources.ontoserver.requests.memory }}
            limits:
              cpu: {{ required "ontoserver.resources.ontoserver.limits.cpu is required" .Values.ontoserver.resources.ontoserver.limits.cpu }}
              memory: {{ required "ontoserver.resources.ontoserver.limits.memory is required" .Values.ontoserver.resources.ontoserver.limits.memory }}
          livenessProbe:
            exec:
              command:
                - /healthcheck.sh
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - /healthcheck.sh
                - "{{- .Values.ontoserver.healthCheckOption }}"
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: JAVA_OPTS
              value: -Xms{{ required "ontoserver.resources.ontoserver.initialHeapSize is required" .Values.ontoserver.resources.ontoserver.initialHeapSize }} -Xmx{{ required ".Values.ontoserver.resources.ontoserver.maxHeapSize is required" .Values.ontoserver.resources.ontoserver.maxHeapSize }}
            - name: LANG
              value: "{{ required "ontoserver.language is required" .Values.ontoserver.language }}.UTF-8"
            - name: LANGUAGE
              value: "{{ required "ontoserver.language is required" .Values.ontoserver.language }}.UTF-8"
            - name: LC_ALL
              value: "{{ required "ontoserver.language is required" .Values.ontoserver.language }}.UTF-8"
            - name: TZ
              value: "{{ required "ontoserver.timeZone is required" .Values.ontoserver.timeZone }}"
            {{- $hostName := required "ontoserver.serverName is required" .Values.ontoserver.serverName }}
            - name: ontoserver.synd.base
              value: https://{{ $hostName }}/synd
            - name: ontoserver.fhir.base
              value: https://{{ $hostName }}/fhir
            - name: ontoserver.formats.html.base
              value: https://{{ $hostName }}/static
            {{- if eq .Values.ontoserver.deployment.type "scaled" }}
            - name: ontoserver.deployment.scaling.dnsQuery
              value: "{{ .Release.Name }}-ontoserver-clustering-service"
            - name: ontoserver.deployment.scaled
              value: "true"
            - name: ontoserver.internal.deployment.scaledReadOnly
              {{- if required "ontoserver.deployment.isReadOnly is required" .Values.ontoserver.deployment.isReadOnly }}
              value: "true"
              {{- else}}
              value: "false"
              {{- end }}
            {{- end}}
            - name: ontoserver.deployment.readOnly
              {{- if required "ontoserver.deployment.isReadOnly is required" .Values.ontoserver.deployment.isReadOnly }}
              value: "true"
              {{- else}}
              value: "false"
              {{- end }}
            {{- range $key, $value := .Values.ontoserver.config }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.ontoserver.secretConfig }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontoserver-secrets
                  key: {{ $key }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-ontoserver-files
              mountPath: /var/onto
            {{- if .Values.ontoserver.customization }}
            - name: customization
              mountPath: /well-known
            {{- end }}
        {{- if and (eq .Values.ontoserver.deployment.type "scaled") .Values.ontoserver.deployment.db.enabled }}
          {{- fail "Scaled deployments require shared database and cannot have the default sidecar database. Set ontoserver.deployment.db.enabled to false and set spring.datasource.url in ontoserver.config to an external db jdbc URL." }}
        {{- end }}
        {{- if and .Values.ontoserver.deployment.db.enabled (not (eq .Values.ontoserver.deployment.type "scaled")) }}
        - name: {{ .Release.Name }}-ontoserver-db
          image: "postgres:{{ required "ontoserver.deployment.db.postgresVersion is required" .Values.ontoserver.deployment.db.postgresVersion }}"
          ports:
            - containerPort: 5432
          resources:
            requests: {{ toJson .Values.ontoserver.resources.db.requests }}
            limits: {{ toJson .Values.ontoserver.resources.db.limits }}
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: LANG
              value: "{{ required "ontoserver.language is required" .Values.ontoserver.language }}.UTF-8"
            - name: LANGUAGE
              value: "{{ required "ontoserver.language is required" .Values.ontoserver.language }}.UTF-8"
            - name: LC_ALL
              value: "{{ required "ontoserver.language is required" .Values.ontoserver.language }}.UTF-8"
            - name: TZ
              value: value: "{{ required "ontoserver.timeZone is required" .Values.ontoserver.timeZone }}"
        {{- end }}

      {{- if not (empty .Values.ontoserver.customization) }}
      volumes:
        - name: customization
          configMap:
            name: {{ .Values.ontoserver.customization }}
      {{- end }}
      
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-ontoserver-files
      spec:
        {{- if .Values.ontoserver.deployment.persistence.existingVolume.enabled }}
        volumeName: {{ .Values.ontoserver.deployment.persistence.existingVolume.name }}
        {{- else }}
        resources:
          requests:
            storage: {{ required "ontoserver.resources.ontoserver.requests.storage is required for Scaled deployments" .Values.ontoserver.resources.ontoserver.requests.storage }}
        accessModes:
          - ReadWriteOnce
        {{- if .Values.ontoserver.deployment.persistence.storageClass.provided.enabled }}
        storageClassName: {{ .Release.Name }}-ontoserver-files-retain
        {{- else}}
        storageClassName: {{ .Values.ontoserver.deployment.persistence.storageClass.name }}
        {{- end }}
        {{- end }}
{{- end }}