apiVersion: v2
name: ontocloak
description: A Helm chart for Ontocloak
type: application
version: 4.0.1
dependencies:
  - name: nginx-ingress
    condition: nginx-ingress.enabled
    version: 2.1.0
    repository: https://helm.nginx.com/stable
  - name: gateway-helm
    condition: envoygateway.controller.install
    version: v1.4.1
    repository: oci://docker.io/envoyproxy
