kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-ontocloak-deployment
  {{- with .Values.ontocloak.deployment.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ontocloak.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ontocloak
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ontocloak
        {{- with .Values.ontocloak.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ontocloak.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if $.Values.ontocloak.deployment.imagePullSecrets  }}
      imagePullSecrets: {{ toJson .Values.ontocloak.deployment.imagePullSecrets }}
      {{- end }}
      {{- if not .Values.ontocloak.migration.skipCheck }}
      initContainers:
        # 1 – DB check
        - name: db-check
          image: postgres:{{ .Values.ontocloak.deployment.db.provided.postgresVersion }}
          command: ["/bin/bash", "-c"]
          env:
            - name: TZ
              value: {{ .Values.ontocloak.timeZone }}
            - name: KC_REALM_NAME
              value: {{ .Values.ontocloak.migration.realmName }}
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_URL_HOST
            {{- if .Values.ontocloak.deployment.db.external.enabled }}
              value: {{ .Values.ontocloak.deployment.db.external.hostName }}
            {{- else }}
              value: {{ .Release.Name }}-ontocloak-db-service
            {{- end }}
            - name: KC_DB_URL_DATABASE
              value: {{ .Values.ontocloak.deployment.db.database }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-db-secret
                  key: username
              value:
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-db-secret
                  key: password
          args:
            - |
              set -e
              # wait up to ~2m for the DB to be reachable
              ready=false
              for i in {1..12}; do
                if PGPASSWORD="$KC_DB_PASSWORD" \
                  psql -h "$KC_DB_URL_HOST" -U "$KC_DB_USERNAME" -d "$KC_DB_URL_DATABASE" -c '\q'; then
                  echo "DB is up!" && ready=true && break
                fi
                echo "Waiting for DB… ($i/12)" && sleep 5
              done
              if ! $ready; then
                echo "ERROR: DB not ready after 60s" >&2
                exit 1
              fi
              # now check for the realm
              if PGPASSWORD="$KC_DB_PASSWORD" \
                psql -h "$KC_DB_URL_HOST" -U "$KC_DB_USERNAME" -d "$KC_DB_URL_DATABASE" \
                  -tAc "SELECT 1 FROM $KC_DB_SCHEMA.realm WHERE name='${KC_REALM_NAME}' LIMIT 1;" \
                | grep -q 1; then
                echo "Realm exists – skipping import" && mkdir -p /work && touch /work/skip
              fi
          volumeMounts:
            - name: workdir
              mountPath: /work
        # 2 – Import if realm doesn't exist in DB
        - name: realm-import
          image: {{ .Values.ontocloak.deployment.image }}
          env:
            - name: TZ
              value: {{ .Values.ontocloak.timeZone }}
            - name: KC_DB_URL_HOST
            {{- if .Values.ontocloak.deployment.db.external.enabled }}
              value: {{ .Values.ontocloak.deployment.db.external.hostName }}
            {{- else }}
              value: {{ .Release.Name }}-ontocloak-db-service
            {{- end }}
            - name: KC_DB_URL_DATABASE
              value: {{ .Values.ontocloak.deployment.db.database }}
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-db-secret
                  key: username
              value:
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-db-secret
                  key: password
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.ontocloak.admin.user }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-keycloak-password
                  key: password                    
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ -f /work/skip ]; then echo "Realm exist in database! Skipping import..."; else kc.sh import --file=/opt/keycloak/data/import/realm.json --override --hostname={{ .Values.ontocloak.serverName }} --proxy edge --optimized; fi
          volumeMounts:
            - name: workdir
              mountPath: /work
            - name: {{ .Release.Name }}-ontocloak-realm-config
              mountPath: /opt/keycloak/data/import
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-ontocloak
          image: {{ required "An ontocloak.image value is required" .Values.ontocloak.deployment.image }}
          imagePullPolicy: Always
          ports:
           - name: http
             containerPort: 8080
           {{- if .Values.ontocloak.metrics.enabled }}
           - name: metrics
             containerPort: 9000
           {{- end }}
          livenessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5
            failureThreshold: 10
          resources:
            requests:
              cpu: {{ .Values.ontocloak.deployment.resources.requests.cpu }}
              memory: {{ .Values.ontocloak.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.ontocloak.deployment.resources.limits.cpu }}
              memory: {{ .Values.ontocloak.deployment.resources.limits.memory }}
          args:
            - start
            - --hostname={{ .Values.ontocloak.serverName }}
            - --proxy edge
            - --optimized
          env:
            - name: TZ
              value: {{ .Values.ontocloak.timeZone }}
            {{- if .Values.ontocloak.metrics.enabled }}
            - name: KC_METRICS_ENABLED
              value: "true"
            {{- end }}
            - name: KC_DB_URL_HOST
            {{- if .Values.ontocloak.deployment.db.external.enabled }}
              value: {{ .Values.ontocloak.deployment.db.external.hostName }}
            {{- else }}
              value: {{ .Release.Name }}-ontocloak-db-service
            {{- end }}
            - name: KC_DB_URL_DATABASE
              value: {{ .Values.ontocloak.deployment.db.database }}
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-db-secret
                  key: username
              value:
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-db-secret
                  key: password
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.ontocloak.admin.user }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ontocloak-keycloak-password
                  key: password
            {{- range $key, $value := .Values.ontocloak.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-ontocloak-properties
              mountPath: /opt/keycloak/conf/agreements.properties
              subPath: ontocloak.properties
            {{- if .Values.ontocloak.customisation }}
            - name: {{ .Release.Name }}-ontocloak-admin-customisation
              mountPath: /opt/keycloak/themes/ontocloak/admin/resources/img/ontoserver-logo.png
              subPath:  ontoserver-logo.png
            - name: {{ .Release.Name }}-ontocloak-login-customisation
              mountPath: /opt/keycloak/themes/ontocloak/login
            {{- end}}
      volumes:
        {{- if not .Values.ontocloak.migration.skipCheck }}
        - name: {{ .Release.Name }}-ontocloak-realm-config
          configMap:
            name: {{ .Release.Name }}-ontocloak-realm-config
        - name: workdir
          emptyDir: {}
        {{- end }}
        - name: {{ .Release.Name }}-ontocloak-properties
          configMap:
            name: {{ .Release.Name }}-ontocloak-properties
      {{- if .Values.ontocloak.deployment.tolerations }}
      tolerations: {{ toJson .Values.ontocloak.deployment.tolerations }}
      {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ontocloak-keycloak-password
data:
  password: {{ .Values.ontocloak.admin.password | b64enc }}
