{{- if .Values.ontocloak.admin.externalSecret.enabled }}
{{- $adminUserKey := include "ontocloak.adminUserKey" . }}
{{- $adminPasswordKey := include "ontocloak.adminPasswordKey" . }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ontocloak.adminSecretName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.ontocloak.admin.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.ontocloak.admin.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.ontocloak.admin.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "ontocloak.adminSecretName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{ $adminUserKey }}: {{ printf "{{ index . %q }}" $adminUserKey | quote }}
        {{ $adminPasswordKey }}: {{ printf "{{ index . %q }}" $adminPasswordKey | quote }}
  data:
    - secretKey: {{ $adminUserKey }}
      remoteRef:
        key: {{ .Values.ontocloak.admin.externalSecret.remoteRef.key }}
        property: {{ .Values.ontocloak.admin.externalSecret.remoteRef.userProperty }}
    - secretKey: {{ $adminPasswordKey }}
      remoteRef:
        key: {{ .Values.ontocloak.admin.externalSecret.remoteRef.key }}
        property: {{ .Values.ontocloak.admin.externalSecret.remoteRef.passwordProperty }}
{{- end }}
{{- if .Values.ontocloak.deployment.db.externalSecret.enabled }}
{{- $dbUserKey := include "ontocloak.dbUserKey" . }}
{{- $dbPasswordKey := include "ontocloak.dbPasswordKey" . }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ontocloak.dbSecretName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.ontocloak.deployment.db.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.ontocloak.deployment.db.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.ontocloak.deployment.db.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "ontocloak.dbSecretName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{ $dbUserKey }}: {{ printf "{{ index . %q }}" $dbUserKey | quote }}
        {{ $dbPasswordKey }}: {{ printf "{{ index . %q }}" $dbPasswordKey | quote }}
  data:
    - secretKey: {{ $dbUserKey }}
      remoteRef:
        key: {{ .Values.ontocloak.deployment.db.externalSecret.remoteRef.key }}
        property: {{ .Values.ontocloak.deployment.db.externalSecret.remoteRef.userProperty }}
    - secretKey: {{ $dbPasswordKey }}
      remoteRef:
        key: {{ .Values.ontocloak.deployment.db.externalSecret.remoteRef.key }}
        property: {{ .Values.ontocloak.deployment.db.externalSecret.remoteRef.passwordProperty }}
{{- end }}
