{{- if .Values.ontocloak.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gw
{{- if or (gt (len .Values.ontocloak.gateway.annotations) 0) .Values.ontocloak.certmanager.enabled }}
  annotations:
    {{- with .Values.ontocloak.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ontocloak.certmanager.enabled }}
    cert-manager.io/issuer:          "{{ .Values.ontocloak.certmanager.clusterIssuerName }}-{{ .Release.Name }}"
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
{{- end }}
spec:
  gatewayClassName: {{ required "ontocloak.gateway.className is required" .Values.ontocloak.gateway.className }}
  infrastructure:
    {{- if gt (len .Values.ontocloak.gateway.infrastructureAnnotations) 0 }}
    annotations: {{ toJson .Values.ontocloak.gateway.infrastructureAnnotations }}
    {{- end }}  
  listeners:
  {{- if .Values.ontocloak.certmanager.enabled }}
  # Cert Manager Listener
    - name: public-http
      protocol: HTTP
      port: 80 # This should be always port 80 as per https://cert-manager.io/docs/configuration/acme/http01/#configuring-the-http-01-gateway-api-solver
      allowedRoutes:
        namespaces:
          from: Same
  {{- end }}
  {{- if eq (len .Values.ontocloak.hostNames) 0 }}
    {{- fail "Minimum one entry is required in ontocloak.hostNames" }}
  {{- end }}
  {{ $releaseName := .Release.Name }}
  {{- range $i, $host := .Values.ontocloak.hostNames }}
    - name: websecure-{{ $i }}
      hostname: {{ $host }}
      port: {{ required "ontocloak.gateway.listenerPortSecure is required" $.Values.ontocloak.gateway.listenerPortSecure }}
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Same
      {{- if $.Values.ontocloak.tls.enabled }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ $.Values.ontocloak.tls.certRef }}
      {{- end }}
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
spec:
  hostnames:
    {{- range .Values.ontocloak.hostNames }}
    - {{ . }}
    {{- end }}
  parentRefs:
  {{- range $i := until (len .Values.ontocloak.hostNames) }}
    - group: gateway.networking.k8s.io
      sectionName: websecure-{{ $i }}
      kind: Gateway
      name: {{ $.Release.Name }}-gw
  {{- end }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Release.Name }}-ontocloak-service
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /auth
      {{- if .Values.ontocloak.gateway.requestTimeout }}
      timeouts:
        request: "{{ .Values.ontocloak.gateway.requestTimeout }}"
        backendRequest: "{{ .Values.ontocloak.gateway.requestTimeout }}"
      {{- end }}
{{- if .Values.ontocloak.certmanager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Release.Name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    email: {{ required "ontocloak.certmanager.email required" .Values.ontocloak.certmanager.email }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: {{ .Release.Name }}-gw
                namespace: {{ .Release.Namespace }}
                kind: Gateway
{{- end }}
{{- end }}