{{- if .Values.ontocloak.ingress.enabled }}
{{- $releaseName := .Release.Name }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ontocloak-ingress
{{- if or (gt (len .Values.ontocloak.ingress.annotations) 0) .Values.ontocloak.certmanager.enabled }}
  annotations:
    {{- range $k, $v := .Values.ontocloak.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- $ngi := index .Values "nginx-ingress" }}
    {{- if and  $ngi.enabled }}
    nginx.org/proxy-buffer-size: "8k"
    {{- end }}
    {{- if .Values.ontocloak.certmanager.enabled }}
    cert-manager.io/cluster-issuer:          "{{ .Values.ontocloak.certmanager.clusterIssuerName }}"
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place:    "true"
    {{- end }}
{{- end }}

spec:
  ingressClassName: {{ required "ontocloak.ingress.className is required" .Values.ontocloak.ingress.className }}
  {{- if .Values.ontocloak.tls.enabled }}
  {{- if eq (len .Values.ontocloak.hostNames) 0 }}
    {{- fail "Minimum one entry is required in ontocloak.hostNames" }}
  {{- end }}
  tls:
    - hosts:
      {{- range .Values.ontocloak.hostNames }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .Values.ontocloak.tls.certRef }}
  {{- end }}
  rules:
  {{- range .Values.ontocloak.hostNames }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}-ontocloak-service
                port:
                  number: 80
  {{- end }}
{{- end }}
