{{- if .Values.ontocloak.deployment.db.provided.persistence.enabledForDeployment }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-files
spec:
  {{- if .Values.ontocloak.deployment.db.provided.persistence.files.existingVolume.enabled }}
  volumeName: {{ .Values.ontocloak.deployment.db.provided.persistence.files.existingVolume.name }}
  {{- end }}
  resources:
    requests:
      storage: "{{ required "ontocloak.deployment.db.provided.persistence.files.diskSize is required" .Values.ontocloak.deployment.db.provided.persistence.files.diskSize }}"
  {{- if .Values.ontoserver.deployment.persistence.files.storageClass.provided.enabled }}
  storageClassName: {{ .Release.Name }}-ontocloak-files
  {{- else }}
  storageClassName: {{ .Values.ontocloak.deployment.db.provided.persistence.files.storageClass.name }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
{{- end }}