kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ontocloak-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-ontocloak
{{ if not .Values.ontocloak.database.external }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ontocloak-db-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-ontocloak-db
{{ end }}