kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ontocloak-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-ontocloak
{{- if not .Values.ontocloak.deployment.db.external }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ontocloak-db-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-ontocloak-db
{{- end }}
{{- if .Values.ontocloak.metrics.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-montocloak-metrics
spec:
  selector:
    app: {{ .Release.Name }}-ontocloak
  ports:
    - name: metrics
      port: 9000
      targetPort: metrics
{{- end }}