{{- /* Validate serverName is in hostNames */ -}}
{{- $sn := .Values.ontocloak.serverName }}
{{- $found := false }}
{{- range .Values.ontocloak.hostNames }}
  {{- if eq . $sn }}
    {{- $found = true }}
  {{- end }}
{{- end }}
{{- if not $found }}
  {{- fail (printf "ontocloak.serverName '%s' must be one of hostNames: %v" $sn .Values.ontocloak.hostNames) }}
{{- end }}

{{- if and .Values.ontocloak.ingress.enabled .Values.ontocloak.gateway.enabled }}
  {{- fail "You must choose between Ingress or Gateway API!" }}
{{- end }}

{{- $ngi := index .Values "nginx-ingress" }}
{{- if and  $ngi.enabled .Values.ontocloak.gateway.enabled }}
  {{- fail "Don't include nginx-ingress-controller when Gateway API is enabled!" }}
{{- end }}
{{- if and  $ngi.enabled  (not .Values.ontocloak.ingress.enabled) }}
  {{- fail "Don't include nginx-ingress-controller when Ingress is disabled!" }}
{{- end }}