apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: atomio-route
spec:
  hostnames:
    {{- range.Values.atomio.gateway.route.hostNames }}
    - {{ . }}
    {{- end }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Release.NAme }}-gw
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Release.Name }}-atomio-service
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
