{{- if $.Values.atomio.openTelemetry.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Release.Name }}-java-instrumentation
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  exporter:
    endpoint: "http://{{ .Release.Name }}-collector:9411"
    exporter: "zipkin"
  java:
    image: otel/autoinstrumentation-java:latest
    env:
      - name: OTEL_TRACES_EXPORTER
        value: "zipkin"
      - name: OTEL_SERVICE_NAME
        value: "{{ .Release.Name }}/{{ .Release.Name }}-atomio"
      - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
        value: "http://{{ .Release.Name }}-collector:9411"
      - name: OTEL_METRICS_EXPORTER
        value: "none"
      - name: OTEL_LOGS_EXPORTER
        value: "none"
      - name: OTEL_PROPAGATORS
        value: "tracecontext,baggage,b3multi"
      - name: OTEL_INSTRUMENTATION_COMMON_ENDUSER_ENABLED
        value: "true"
---
apiVersion: opentelemetry.io/v1beta1  # Change from v1alpha1 to v1beta1
kind: OpenTelemetryCollector
metadata:
 name: {{ .Release.Name }}
 labels:
   app: opentelemetry
   component: otel-operator
spec:
  config:
   receivers:
     zipkin:
       endpoint: 0.0.0.0:9411
     otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
   processors:
     memory_limiter:
       check_interval: 1s
       limit_percentage: 75
       spike_limit_percentage: 15
     filter/health_checks:
       traces:
         span:
           # FHIR metadata spans
           - attributes["http.route"] == "/actuator/health"
           - name == "get /actuator/health"
           - attributes["http.route"] == "/\*"
           - name == "get /\*"

     batch:
       send_batch_size: 1000
       timeout: 0s
   exporters:
     debug:
       verbosity: detailed
     otlp:
       endpoint: "{{- .Values.atomio.openTelemetry.otlpEndpoint }}"
       tls:
         insecure: true
     zipkin:
       endpoint: "{{- .Values.atomio.openTelemetry.zipkinEndpoint }}"
       tls:
         insecure: true
   service:
     pipelines:
       traces:
         receivers:
          - otlp
          - zipkin
         processors:
          - memory_limiter
          - batch
         exporters:
          - zipkin
          - otlp

{{- end }}