kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-atomio-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-atomio
{{ if and .Values.atomio.database.postgres.enabled (not .Values.atomio.database.postgres.external.hostName) }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-atomio-db-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-atomio-db
{{ end }}