apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: contour-{{ .Release.Name }}
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    group: projectcontour.io
    kind: ContourDeployment
    name: {{ .Release.Name }}-contourdeployment
    namespace: {{ .Release.Namespace }}