{{- if .Values.openTelemetry.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
 name: {{ .Release.Name }}
 labels:
   app: opentelemetry
   component: otel-operator
spec:
  config:
   receivers:
     otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
   processors:
     memory_limiter:
       check_interval: 1s
       limit_percentage: 75
       spike_limit_percentage: 15
     batch:
       send_batch_size: 100
       timeout: 1s
       send_batch_max_size: 500
   exporters:
     debug:
       verbosity: detailed
     otlp:
       endpoint: "{{- .Values.openTelemetry.otlpEndpoint }}"
       tls:
         insecure: true
   service:
     pipelines:
       traces:
         receivers:
          - otlp
         processors:
          - memory_limiter
          - batch
         exporters:
          #- debug
          - otlp
{{- end }}