{{- if .Values.ipfilter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ip-filter-service
spec:
  selector:
    app: ip-filter
  ports:
  - name: http
    port: 8181
    targetPort: 8181
  - name: grpc
    port: 9191
    targetPort: 9191
{{- end }}