apiVersion: v2
name: ontoserver-helm
description: Ontoserver FHIR terminology server helm chart
type: application
version: 1.0.0
dependencies:
  - name: nginx-ingress
    condition: ingress.nginx.enabled
    version: ^2.0.1
    repository: https://helm.nginx.com/stable
