ontoserver:
  deployment:
    kind: Deployment # Or StatefulSet - Deployment will be default
    type: single # Options are single or scaled
    deploymentStrategy: RollingUpdate # When using Deployment Kind this sets the K8s deployment strategy
    podDistruptionBudget: # Only used when deployment type is scaled
      enabled: true 
      minAvailable: 1 
      maxUnavailable: false # If you set this, set minAvaliable to false
      unhealthyPodEvictionPolicy: false # Optional "Fail"  # or "DoNotEvict"
  serverName: localhost # Must match a hostName
  hostNames:
    - locahost
  image: quay.io/aehrc/ontoserver:ctsa-6
  imagePullPolicy: Always
  imagePullSecrets: []
  timeZone: UTC
  language: en_US
  replicas: 1 # Set min. 2 if the deployment type is scaled or 0 to turn Onto off
  resources:
    ontoserver:
      requests:
        cpu: 2
        memory: 4G
        storage: 10G
      limits:
        cpu: 2
        memory: 4G
      initialHeapSize: 2800m
      maxHeapSize: 2800m
  healthCheckOption: -s
  certmanager:
    enabled: true
  gateway:
    enabled: true
    listenerPortSecure: 443 # Depends on the gateway class - Traefik is 8443
    certmanager: 
      enabled: true
      email: noreply@example.com
    annotations: {}
    infrastructureAnnotations: {}
    className: envoy-gateway-class
    requestTimeout: 120s
  ingress:
    annotations: {}
    enabled: false
    class: ontoserver-nginx
    tlsEnabled: false
  tolerations: []
  storageProvisioner: disk.csi.azure.com
  storageParameters:
    skuName: Premium_LRS
    kind: Managed
  customization: false
  config:
    ONTOSERVER_INSECURE: "true"
    ontoserver.deployment.scaled: "true"
    ontoserver.internal.deployment.scaledReadOnly: "false"
  secretConfig: {}

nginx-ingress:
  controller:
    ingressClass: ontoserver-nginx
    ingressClassByName: true
