apiVersion: v2
name: atomio
description: A Helm chart for Atomio
type: application
version: 3.0.1
dependencies:
  - name: nginx-ingress
    condition: atomio.ingress.nginx
    version: 1.4.2
    repository: https://helm.nginx.com/stable
