apiVersion: v2
name: atomio
description: A Helm chart for Atomio
type: application
version: 3.1.2
dependencies:
  - name: nginx-ingress
    condition: atomio.ingress.nginx
    version: 2.0.1
    repository: https://helm.nginx.com/stable
